import "./globals.css";

import { Poppins } from "next/font/google";

import { Sidebar } from "@/components/sidebar";

import { MobileNav } from "@/components/mobile-nav";
import { Toaster } from "@/components/ui/toaster";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // You can add any other weights needed
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <div className="flex min-h-screen flex-col md:flex-row">
        <Toaster />
          {/* Desktop Sidebar - hidden on mobile */}
          <div className="hidden md:block">
            <Sidebar />
          </div>

          {/* Mobile Navigation - visible only on mobile */}
          <div className="md:hidden">
            <MobileNav />
          </div>

          <main className="flex-1 overflow-auto p-4 md:p-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
